name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fetch lovr exe
        run: |
          curl https://lovr.org/download -L -o lovr.zip
          unzip lovr.zip -d layout

      - name: Package Layout
        run: |
          cd src
          zip -0qr layout.lovr .
          cat ../layout/lovr.exe layout.lovr > ../layout/layout.exe
          cd ..
          rm layout/lovr.exe
          zip -9qr layout.zip layout/

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Layout ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Layout artifact
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./layout.zip
          asset_name: layout.zip
          asset_content_type: application/zip